num1 = float(input('Pleuse enter a number: '))
num2 = float(input('Enter a number one more time: '))

print('num1 + num2 =', num1 + num2)
print('num1 - num2 =', num1 - num2)
print('num1 * num2 =', num1 * num2)
print('num1 ** num2 =', num1 ** num2)
print('num1 / num2 =', num1 / num2)
print('num1 // num2 =', num1 // num2)
print('num1 % num2 =', num1 % num2)
